//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resxul.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resxul.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool to simplify compilation of .resx files into satellite assemblies..
        /// </summary>
        public static string App_Wnd_Desc {
            get {
                return ResourceManager.GetString("App_Wnd_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start application after compilation.
        /// </summary>
        public static string AutoStartApp {
            get {
                return ResourceManager.GetString("AutoStartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile &amp; Run.
        /// </summary>
        public static string CompileAndRun {
            get {
                return ResourceManager.GetString("CompileAndRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (doesn&apos;t exist).
        /// </summary>
        public static string File_NotExist {
            get {
                return ResourceManager.GetString("File_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected.
        /// </summary>
        public static string File_NotSelected {
            get {
                return ResourceManager.GetString("File_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource language.
        /// </summary>
        public static string Language_ResourceLanguage {
            get {
                return ResourceManager.GetString("Language_ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resx file not selected.
        /// </summary>
        public static string Language_ResxNotSelected {
            get {
                return ResourceManager.GetString("Language_ResxNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language tag.
        /// </summary>
        public static string Language_Tag {
            get {
                return ResourceManager.GetString("Language_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect.
        /// </summary>
        public static string Language_UnableToDetect {
            get {
                return ResourceManager.GetString("Language_UnableToDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open output folder after compilation.
        /// </summary>
        public static string OpenOutputFolder {
            get {
                return ResourceManager.GetString("OpenOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add profile.
        /// </summary>
        public static string Profile_Add {
            get {
                return ResourceManager.GetString("Profile_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application file path.
        /// </summary>
        public static string Profile_AppFilePath {
            get {
                return ResourceManager.GetString("Profile_AppFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application folder.
        /// </summary>
        public static string Profile_AppFolder {
            get {
                return ResourceManager.GetString("Profile_AppFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string Profile_AppName {
            get {
                return ResourceManager.GetString("Profile_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application command line arguments (optional).
        /// </summary>
        public static string Profile_CommandLineArgs {
            get {
                return ResourceManager.GetString("Profile_CommandLineArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot; profile?.
        /// </summary>
        public static string Profile_Delete_Title {
            get {
                return ResourceManager.GetString("Profile_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select profile to start.
        /// </summary>
        public static string Profile_EmptyState_SelectProfileToStart {
            get {
                return ResourceManager.GetString("Profile_EmptyState_SelectProfileToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add profile....
        /// </summary>
        public static string Profile_Menu_Add {
            get {
                return ResourceManager.GetString("Profile_Menu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        public static string Profile_Menu_Delete {
            get {
                return ResourceManager.GetString("Profile_Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile....
        /// </summary>
        public static string Profile_Menu_Edit {
            get {
                return ResourceManager.GetString("Profile_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string Profile_Name {
            get {
                return ResourceManager.GetString("Profile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not populated. Check profile and variables.
        /// </summary>
        public static string Profile_NotPopulated {
            get {
                return ResourceManager.GetString("Profile_NotPopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not selected.
        /// </summary>
        public static string Profile_NotSelected {
            get {
                return ResourceManager.GetString("Profile_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populated.
        /// </summary>
        public static string Profile_Populated {
            get {
                return ResourceManager.GetString("Profile_Populated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resx namespace.
        /// </summary>
        public static string Profile_ResxNamespace {
            get {
                return ResourceManager.GetString("Profile_ResxNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite assembly name.
        /// </summary>
        public static string Profile_SatelliteAssemblyName {
            get {
                return ResourceManager.GetString("Profile_SatelliteAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly output folder.
        /// </summary>
        public static string Profile_SatelliteAssemblyOutputFolder {
            get {
                return ResourceManager.GetString("Profile_SatelliteAssemblyOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Profile_Save {
            get {
                return ResourceManager.GetString("Profile_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select profile.
        /// </summary>
        public static string Profile_Select {
            get {
                return ResourceManager.GetString("Profile_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A profile is required for correct compilation of the assembly.
        ///Special variables below and environment variables can be used..
        /// </summary>
        public static string Profile_Wnd_Desc {
            get {
                return ResourceManager.GetString("Profile_Wnd_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Edit profile.
        /// </summary>
        public static string Profile_Wnd_Title {
            get {
                return ResourceManager.GetString("Profile_Wnd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resx file.
        /// </summary>
        public static string ResxFile {
            get {
                return ResourceManager.GetString("ResxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching application executable....
        /// </summary>
        public static string SearchingAppExecutable {
            get {
                return ResourceManager.GetString("SearchingAppExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching resgen / al....
        /// </summary>
        public static string SearchingTools {
            get {
                return ResourceManager.GetString("SearchingTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify application file path (optional).
        /// </summary>
        public static string SpecifyAppPath {
            get {
                return ResourceManager.GetString("SpecifyAppPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify path to .resx file.
        /// </summary>
        public static string SpecifyResxPath {
            get {
                return ResourceManager.GetString("SpecifyResxPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify resgen and al folder path.
        /// </summary>
        public static string SpecifyToolsFolderPath {
            get {
                return ResourceManager.GetString("SpecifyToolsFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start application.
        /// </summary>
        public static string StartApp {
            get {
                return ResourceManager.GetString("StartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred..
        /// </summary>
        public static string UnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("UnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string Validation_FieldRequired {
            get {
                return ResourceManager.GetString("Validation_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string Validation_FileNotFound {
            get {
                return ResourceManager.GetString("Validation_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View log file in {0} for more details..
        /// </summary>
        public static string ViewLogFile {
            get {
                return ResourceManager.GetString("ViewLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
